const ActionType = {
  CHOOSE_CITY: 'CHOOSE_CITY',
  LOAD_DATA: 'LOAD_DATA',
  REQUIRED_AUTHORIZATION: 'REQUIRED_AUTHORIZATION',
  SEND_COMMENTS: 'SEND_COMMENTS',
  LOAD_COMMENTS: 'LOAD_COMMENTS',
}

export {ActionType}
